openapi: 3.0.3
info:
  title: Nav Rinasak API
  description: API for 책 behandle Nav Rinasaker
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: '/'
tags:
  - name: Rinasaker
    description: >-
      API for 책 behandle Nav Rinasaker. En Nav Rinasak er en 
      knytning mellom en fagsak i Nav og en Rinasak i RINA.
  - name: Sed
    description: >-
      API for 책 behandle Sed h책ndtering og journalstatus i Nav Rinasak

paths:
  '/api/v1/rinasaker':
    $ref: 'rinasaker/operations_rot.yaml'
  '/api/v1/rinasaker/finn':
    $ref: 'rinasaker/operations_finn.yaml'
  '/api/v1/rinasaker/{rinasakId}':
    $ref: 'rinasaker/operations_byRinasakId.yaml'
  '/api/v1/rinasaker/{rinasakId}/dokumenter':
    $ref: 'dokumenter/operations_rot.yaml'
  '/api/v1/rinasaker/{rinasakId}/fagsak':
    $ref: 'fagsaker/operations_rot.yaml'
  '/api/v1/sed/journalstatuser':
    $ref: 'sed/operations_rot.yaml'
  '/api/v1/sed/journalstatuser/finn':
    $ref: 'sed/operations_finn.yaml'
