openapi: 3.0.3
info:
  title: Nav Rinasak API
  description: API for å behandle NAV Rinasaker
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Nav Rinasak API
    description: >-
      API for å behandle NAV Rinasaker. En NAV Rinasak er en 
      knytning mellom en fagsak i NAV og en Rinasak i RINA.

paths:
  '/rinasaker':
    $ref: 'rinasaker/operations_rot.yaml'
  '/rinasaker/finn':
    $ref: 'rinasaker/operations_finn.yaml'
  '/rinasaker/{rinasakId}':
    $ref: 'rinasaker/operations_byRinasakId.yaml'
  '/rinasaker/{rinasakId}/dokumenter':
    $ref: 'dokumenter/operations_rot.yaml'
  '/sed/journalstatuser':
    $ref: 'sed/operations_rot.yaml'
  '/sed/journalstatuser/finn':
    $ref: 'sed/operations_finn.yaml'
