name: eux-nav-rinasak
ingress: https://eux-nav-rinasak.intern.dev.nav.no
database:
  name: eux-nav-rinasak-db
  tier: db-custom-1-614
application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis
cluster:
  fss: dev-fss
  gcp: dev-gcp
