name: eux-nav-rinasak
ingress: https://eux-nav-rinasak.intern.nav.no
database:
  name: eux-nav-rinasak-db
  tier: db-custom-1-3840
application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis
  eux-journal:
    name: eux-journal
    namespace: eessibasis
  eux-nav-rinasak-datasync:
    name: eux-nav-rinasak-datasync
    namespace: eessibasis
  eux-fagmodul-journalfoering:
    name: eux-fagmodul-journalfoering
    namespace: eessibasis
cluster:
  fss: prod-fss
  gcp: prod-gcp
