name: eux-nav-rinasak
ingress: https://eux-nav-rinasak.intern.nav.no
database:
  name: eux-nav-rinasak-db
  tier: db-custom-1-512
application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis
cluster:
  fss: prod-fss
  gcp: prod-gcp
