opprettetTidspunkt:
  type: string
  format: date-time
  description: Dato da entiteten ble opprettet.

opprettetBruker:
  type: string
  description: Brukeren som opprettet entiteten. Kan være skalbehandler eller system.
